### ISSUE TITLE
Web Developer Checklist

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/peterdesmet.github.com#1]
Based on http://webdevchecklist.com/

## Best practices

* [x] Fix broken links
* [x] Spell-check
* [ ] Check website in all browsers
* [x] Remove 'www' subdomain

## Mobile

* [ ] MobileOK score of 75+
* [ ] Use 'viewport' meta-tag
* [x] Use correct input types
* [x] Manual check using emulators

## Analytics

* [x] Uptime monitoring
* [x] Traffic analysis

## Performance

* [x] Google Page Speed score of 90+
* [x] Yahoo YSlow score of 85+
* [x] Optimize HTTP headers
* [x] Optimize images

## Usability

* [ ] HTML5 compatibility check
* [ ] Custom 404 page
* [x] Favicon
* [x] Use friendly URLs

### Optional

* [x] Add search feature
* [ ] Environment Integration

## Semantics

* [x] Add meaning with Microdata
* [x] Check the semantics

## SEO

* [x] SenSEO score of 85+
* [ ] Google Rich Snippets
* [x] robots.txt
* [ ] XML sitemap

## Code quality

* [ ] HTML validation
* [x] CSS validation
* [ ] Run CSS Lint
* [x] Run JSLint/JSHint
* [x] World ready
* [x] Automated testing

## Accessibility

* [ ] Accessibility validation
* [ ] Color contrast
* [ ] WAI-ARIA Landmarks

## Security

* [x] Follow best practices
* [x] Cross-site scripting
* [x] Cross-site request forgery

### Optional

* [x] Secure connection (SSL)
* [x] HTTP Strict Transport Security

## Social Media

* [ ] Open Graph protocol
* [ ] Twitter Cards
* [ ] Facebook Insights

## ...and finally

* [x] Add humans.txt

**Comment by peterdesmet** [comment]
Has been open long enough... closing
